//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 11:48:15 PM CET 
//


package si.um.feri.obu.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the si.um.feri.obu package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetDriveHistoryResponse_QNAME = new QName("http://feri.um.si/obu", "getDriveHistoryResponse");
    private final static QName _GetLocationResponse_QNAME = new QName("http://feri.um.si/obu", "getLocationResponse");
    private final static QName _ReceiveNotificationRequest_QNAME = new QName("http://feri.um.si/obu", "receiveNotificationRequest");
    private final static QName _GetOBUIdResponse_QNAME = new QName("http://feri.um.si/obu", "getOBUIdResponse");
    private final static QName _GetCarCommandListResponse_QNAME = new QName("http://feri.um.si/obu", "getCarCommandListResponse");
    private final static QName _GetCarErrorsResponse_QNAME = new QName("http://feri.um.si/obu", "getCarErrorsResponse");
    private final static QName _GetCarParameterValueResponse_QNAME = new QName("http://feri.um.si/obu", "getCarParameterValueResponse");
    private final static QName _GetLocationRequest_QNAME = new QName("http://feri.um.si/obu", "getLocationRequest");
    private final static QName _GetCarCommandListRequest_QNAME = new QName("http://feri.um.si/obu", "getCarCommandListRequest");
    private final static QName _GetCarErrorsRequest_QNAME = new QName("http://feri.um.si/obu", "getCarErrorsRequest");
    private final static QName _SendCarCommandResponse_QNAME = new QName("http://feri.um.si/obu", "sendCarCommandResponse");
    private final static QName _GetDriveHistoryRequest_QNAME = new QName("http://feri.um.si/obu", "getDriveHistoryRequest");
    private final static QName _GetCarParameterListResponse_QNAME = new QName("http://feri.um.si/obu", "getCarParameterListResponse");
    private final static QName _GetCarParameterValueRequest_QNAME = new QName("http://feri.um.si/obu", "getCarParameterValueRequest");
    private final static QName _SendCarCommandRequest_QNAME = new QName("http://feri.um.si/obu", "sendCarCommandRequest");
    private final static QName _GetOBUIdRequest_QNAME = new QName("http://feri.um.si/obu", "getOBUIdRequest");
    private final static QName _ReceiveNotificationResponse_QNAME = new QName("http://feri.um.si/obu", "receiveNotificationResponse");
    private final static QName _GetCarParameterListRequest_QNAME = new QName("http://feri.um.si/obu", "getCarParameterListRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: si.um.feri.obu
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDriveHistoryResponse }
     * 
     */
    public GetDriveHistoryResponse createGetDriveHistoryResponse() {
        return new GetDriveHistoryResponse();
    }

    /**
     * Create an instance of {@link GetLocationResponse }
     * 
     */
    public GetLocationResponse createGetLocationResponse() {
        return new GetLocationResponse();
    }

    /**
     * Create an instance of {@link ReceiveNotificationRequest }
     * 
     */
    public ReceiveNotificationRequest createReceiveNotificationRequest() {
        return new ReceiveNotificationRequest();
    }

    /**
     * Create an instance of {@link GetOBUIdResponse }
     * 
     */
    public GetOBUIdResponse createGetOBUIdResponse() {
        return new GetOBUIdResponse();
    }

    /**
     * Create an instance of {@link GetCarCommandListResponse }
     * 
     */
    public GetCarCommandListResponse createGetCarCommandListResponse() {
        return new GetCarCommandListResponse();
    }

    /**
     * Create an instance of {@link GetCarErrorsResponse }
     * 
     */
    public GetCarErrorsResponse createGetCarErrorsResponse() {
        return new GetCarErrorsResponse();
    }

    /**
     * Create an instance of {@link GetCarParameterValueResponse }
     * 
     */
    public GetCarParameterValueResponse createGetCarParameterValueResponse() {
        return new GetCarParameterValueResponse();
    }

    /**
     * Create an instance of {@link GetLocationRequest }
     * 
     */
    public GetLocationRequest createGetLocationRequest() {
        return new GetLocationRequest();
    }

    /**
     * Create an instance of {@link GetCarCommandListRequest }
     * 
     */
    public GetCarCommandListRequest createGetCarCommandListRequest() {
        return new GetCarCommandListRequest();
    }

    /**
     * Create an instance of {@link GetCarErrorsRequest }
     * 
     */
    public GetCarErrorsRequest createGetCarErrorsRequest() {
        return new GetCarErrorsRequest();
    }

    /**
     * Create an instance of {@link SendCarCommandResponse }
     * 
     */
    public SendCarCommandResponse createSendCarCommandResponse() {
        return new SendCarCommandResponse();
    }

    /**
     * Create an instance of {@link GetDriveHistoryRequest }
     * 
     */
    public GetDriveHistoryRequest createGetDriveHistoryRequest() {
        return new GetDriveHistoryRequest();
    }

    /**
     * Create an instance of {@link GetCarParameterListResponse }
     * 
     */
    public GetCarParameterListResponse createGetCarParameterListResponse() {
        return new GetCarParameterListResponse();
    }

    /**
     * Create an instance of {@link GetCarParameterValueRequest }
     * 
     */
    public GetCarParameterValueRequest createGetCarParameterValueRequest() {
        return new GetCarParameterValueRequest();
    }

    /**
     * Create an instance of {@link SendCarCommandRequest }
     * 
     */
    public SendCarCommandRequest createSendCarCommandRequest() {
        return new SendCarCommandRequest();
    }

    /**
     * Create an instance of {@link GetOBUIdRequest }
     * 
     */
    public GetOBUIdRequest createGetOBUIdRequest() {
        return new GetOBUIdRequest();
    }

    /**
     * Create an instance of {@link ReceiveNotificationResponse }
     * 
     */
    public ReceiveNotificationResponse createReceiveNotificationResponse() {
        return new ReceiveNotificationResponse();
    }

    /**
     * Create an instance of {@link GetCarParameterListRequest }
     * 
     */
    public GetCarParameterListRequest createGetCarParameterListRequest() {
        return new GetCarParameterListRequest();
    }

    /**
     * Create an instance of {@link TrackPoint }
     * 
     */
    public TrackPoint createTrackPoint() {
        return new TrackPoint();
    }

    /**
     * Create an instance of {@link CarError }
     * 
     */
    public CarError createCarError() {
        return new CarError();
    }

    /**
     * Create an instance of {@link Track }
     * 
     */
    public Track createTrack() {
        return new Track();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDriveHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getDriveHistoryResponse")
    public JAXBElement<GetDriveHistoryResponse> createGetDriveHistoryResponse(GetDriveHistoryResponse value) {
        return new JAXBElement<GetDriveHistoryResponse>(_GetDriveHistoryResponse_QNAME, GetDriveHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLocationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getLocationResponse")
    public JAXBElement<GetLocationResponse> createGetLocationResponse(GetLocationResponse value) {
        return new JAXBElement<GetLocationResponse>(_GetLocationResponse_QNAME, GetLocationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiveNotificationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "receiveNotificationRequest")
    public JAXBElement<ReceiveNotificationRequest> createReceiveNotificationRequest(ReceiveNotificationRequest value) {
        return new JAXBElement<ReceiveNotificationRequest>(_ReceiveNotificationRequest_QNAME, ReceiveNotificationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOBUIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getOBUIdResponse")
    public JAXBElement<GetOBUIdResponse> createGetOBUIdResponse(GetOBUIdResponse value) {
        return new JAXBElement<GetOBUIdResponse>(_GetOBUIdResponse_QNAME, GetOBUIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarCommandListResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarCommandListResponse")
    public JAXBElement<GetCarCommandListResponse> createGetCarCommandListResponse(GetCarCommandListResponse value) {
        return new JAXBElement<GetCarCommandListResponse>(_GetCarCommandListResponse_QNAME, GetCarCommandListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarErrorsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarErrorsResponse")
    public JAXBElement<GetCarErrorsResponse> createGetCarErrorsResponse(GetCarErrorsResponse value) {
        return new JAXBElement<GetCarErrorsResponse>(_GetCarErrorsResponse_QNAME, GetCarErrorsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarParameterValueResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarParameterValueResponse")
    public JAXBElement<GetCarParameterValueResponse> createGetCarParameterValueResponse(GetCarParameterValueResponse value) {
        return new JAXBElement<GetCarParameterValueResponse>(_GetCarParameterValueResponse_QNAME, GetCarParameterValueResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLocationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getLocationRequest")
    public JAXBElement<GetLocationRequest> createGetLocationRequest(GetLocationRequest value) {
        return new JAXBElement<GetLocationRequest>(_GetLocationRequest_QNAME, GetLocationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarCommandListRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarCommandListRequest")
    public JAXBElement<GetCarCommandListRequest> createGetCarCommandListRequest(GetCarCommandListRequest value) {
        return new JAXBElement<GetCarCommandListRequest>(_GetCarCommandListRequest_QNAME, GetCarCommandListRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarErrorsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarErrorsRequest")
    public JAXBElement<GetCarErrorsRequest> createGetCarErrorsRequest(GetCarErrorsRequest value) {
        return new JAXBElement<GetCarErrorsRequest>(_GetCarErrorsRequest_QNAME, GetCarErrorsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendCarCommandResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "sendCarCommandResponse")
    public JAXBElement<SendCarCommandResponse> createSendCarCommandResponse(SendCarCommandResponse value) {
        return new JAXBElement<SendCarCommandResponse>(_SendCarCommandResponse_QNAME, SendCarCommandResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDriveHistoryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getDriveHistoryRequest")
    public JAXBElement<GetDriveHistoryRequest> createGetDriveHistoryRequest(GetDriveHistoryRequest value) {
        return new JAXBElement<GetDriveHistoryRequest>(_GetDriveHistoryRequest_QNAME, GetDriveHistoryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarParameterListResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarParameterListResponse")
    public JAXBElement<GetCarParameterListResponse> createGetCarParameterListResponse(GetCarParameterListResponse value) {
        return new JAXBElement<GetCarParameterListResponse>(_GetCarParameterListResponse_QNAME, GetCarParameterListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarParameterValueRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarParameterValueRequest")
    public JAXBElement<GetCarParameterValueRequest> createGetCarParameterValueRequest(GetCarParameterValueRequest value) {
        return new JAXBElement<GetCarParameterValueRequest>(_GetCarParameterValueRequest_QNAME, GetCarParameterValueRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendCarCommandRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "sendCarCommandRequest")
    public JAXBElement<SendCarCommandRequest> createSendCarCommandRequest(SendCarCommandRequest value) {
        return new JAXBElement<SendCarCommandRequest>(_SendCarCommandRequest_QNAME, SendCarCommandRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOBUIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getOBUIdRequest")
    public JAXBElement<GetOBUIdRequest> createGetOBUIdRequest(GetOBUIdRequest value) {
        return new JAXBElement<GetOBUIdRequest>(_GetOBUIdRequest_QNAME, GetOBUIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiveNotificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "receiveNotificationResponse")
    public JAXBElement<ReceiveNotificationResponse> createReceiveNotificationResponse(ReceiveNotificationResponse value) {
        return new JAXBElement<ReceiveNotificationResponse>(_ReceiveNotificationResponse_QNAME, ReceiveNotificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCarParameterListRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://feri.um.si/obu", name = "getCarParameterListRequest")
    public JAXBElement<GetCarParameterListRequest> createGetCarParameterListRequest(GetCarParameterListRequest value) {
        return new JAXBElement<GetCarParameterListRequest>(_GetCarParameterListRequest_QNAME, GetCarParameterListRequest.class, null, value);
    }

}
