//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 05:55:55 PM CET 
//


package si.um.feri.obu.domain.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for carParameter.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="carParameter">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FUEL"/>
 *     &lt;enumeration value="OIL"/>
 *     &lt;enumeration value="TEMPERATURE"/>
 *     &lt;enumeration value="TYRE_PRESSURE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "carParameter")
@XmlEnum
public enum CarParameter {

    FUEL,
    OIL,
    TEMPERATURE,
    TYRE_PRESSURE;

    public String value() {
        return name();
    }

    public static CarParameter fromValue(String v) {
        return valueOf(v);
    }

}
