//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the
// source schema.
// Generated on: 2015.11.20 at 10:30:57 AM CET 
//


package si.um.feri.obu.domain.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for geoLocation complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 * <p>
 * <pre>
 * &lt;complexType name="geoLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lat" type="{http://www.w3
 *         .org/2001/XMLSchema}float"/>
 *         &lt;element name="lon" type="{http://www.w3
 *         .org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "geoLocation", propOrder = {
        "lat",
        "lon"
})
public class GeoLocation {

    protected float lat;
    protected float lon;

    /**
     * Gets the value of the lat property.
     */
    public float getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     */
    public void setLat(float value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     */
    public float getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     */
    public void setLon(float value) {
        this.lon = value;
    }

}
