//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 10:15:57 AM CET 
//


package si.um.feri.obu.domain.xjc;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for getLocationResponse complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="getLocationResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gepLocation" type="{http://feri.um.si/obu}geoLocation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getLocationResponse", propOrder = {
        "gepLocation"
})
@XmlRootElement(name = "getLocationResponse")
public class GetLocationResponse {

    @XmlElement(required = true)
    protected GeoLocation gepLocation;

    /**
     * Gets the value of the gepLocation property.
     *
     * @return possible object is
     * {@link GeoLocation }
     */
    public GeoLocation getGepLocation() {
        return gepLocation;
    }

    /**
     * Sets the value of the gepLocation property.
     *
     * @param value allowed object is
     *              {@link GeoLocation }
     */
    public void setGepLocation(GeoLocation value) {
        this.gepLocation = value;
    }

}
