//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 01:10:11 PM CET 
//


package si.um.feri.obu.domain.xjc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the si.um.feri.obu.domain.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: si.um.feri.obu.domain.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDriveHistoryResponse }
     * 
     */
    public GetDriveHistoryResponse createGetDriveHistoryResponse() {
        return new GetDriveHistoryResponse();
    }

    /**
     * Create an instance of {@link Track }
     * 
     */
    public Track createTrack() {
        return new Track();
    }

    /**
     * Create an instance of {@link GetLocationResponse }
     * 
     */
    public GetLocationResponse createGetLocationResponse() {
        return new GetLocationResponse();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link ReceiveNotificationRequest }
     * 
     */
    public ReceiveNotificationRequest createReceiveNotificationRequest() {
        return new ReceiveNotificationRequest();
    }

    /**
     * Create an instance of {@link GetOBUIdResponse }
     * 
     */
    public GetOBUIdResponse createGetOBUIdResponse() {
        return new GetOBUIdResponse();
    }

    /**
     * Create an instance of {@link GetCarCommandListResponse }
     * 
     */
    public GetCarCommandListResponse createGetCarCommandListResponse() {
        return new GetCarCommandListResponse();
    }

    /**
     * Create an instance of {@link GetCarErrorsResponse }
     * 
     */
    public GetCarErrorsResponse createGetCarErrorsResponse() {
        return new GetCarErrorsResponse();
    }

    /**
     * Create an instance of {@link CarError }
     * 
     */
    public CarError createCarError() {
        return new CarError();
    }

    /**
     * Create an instance of {@link GetCarParameterValueResponse }
     * 
     */
    public GetCarParameterValueResponse createGetCarParameterValueResponse() {
        return new GetCarParameterValueResponse();
    }

    /**
     * Create an instance of {@link GetLocationRequest }
     * 
     */
    public GetLocationRequest createGetLocationRequest() {
        return new GetLocationRequest();
    }

    /**
     * Create an instance of {@link GetCarCommandListRequest }
     * 
     */
    public GetCarCommandListRequest createGetCarCommandListRequest() {
        return new GetCarCommandListRequest();
    }

    /**
     * Create an instance of {@link GetCarErrorsRequest }
     * 
     */
    public GetCarErrorsRequest createGetCarErrorsRequest() {
        return new GetCarErrorsRequest();
    }

    /**
     * Create an instance of {@link SendCarCommandResponse }
     * 
     */
    public SendCarCommandResponse createSendCarCommandResponse() {
        return new SendCarCommandResponse();
    }

    /**
     * Create an instance of {@link GetDriveHistoryRequest }
     * 
     */
    public GetDriveHistoryRequest createGetDriveHistoryRequest() {
        return new GetDriveHistoryRequest();
    }

    /**
     * Create an instance of {@link GetCarParameterListResponse }
     * 
     */
    public GetCarParameterListResponse createGetCarParameterListResponse() {
        return new GetCarParameterListResponse();
    }

    /**
     * Create an instance of {@link GetCarParameterValueRequest }
     * 
     */
    public GetCarParameterValueRequest createGetCarParameterValueRequest() {
        return new GetCarParameterValueRequest();
    }

    /**
     * Create an instance of {@link SendCarCommandRequest }
     * 
     */
    public SendCarCommandRequest createSendCarCommandRequest() {
        return new SendCarCommandRequest();
    }

    /**
     * Create an instance of {@link GetOBUIdRequest }
     * 
     */
    public GetOBUIdRequest createGetOBUIdRequest() {
        return new GetOBUIdRequest();
    }

    /**
     * Create an instance of {@link ReceiveNotificationResponse }
     * 
     */
    public ReceiveNotificationResponse createReceiveNotificationResponse() {
        return new ReceiveNotificationResponse();
    }

    /**
     * Create an instance of {@link GetCarParameterListRequest }
     * 
     */
    public GetCarParameterListRequest createGetCarParameterListRequest() {
        return new GetCarParameterListRequest();
    }

    /**
     * Create an instance of {@link TrackPoint }
     * 
     */
    public TrackPoint createTrackPoint() {
        return new TrackPoint();
    }

}
