
package si.um.feri.obu.wsservice.avtoservis2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TehnicnaPomocImplService", targetNamespace = "http://smart.road.si/pomoc", wsdlLocation = "http://164.8.251.196:8080/Servis2/TehnicnaPomocImpl?wsdl")
public class TehnicnaPomocImplService
    extends Service
{

    private final static URL TEHNICNAPOMOCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TEHNICNAPOMOCIMPLSERVICE_EXCEPTION;
    private final static QName TEHNICNAPOMOCIMPLSERVICE_QNAME = new QName("http://smart.road.si/pomoc", "TehnicnaPomocImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://164.8.251.196:8080/Servis2/TehnicnaPomocImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEHNICNAPOMOCIMPLSERVICE_WSDL_LOCATION = url;
        TEHNICNAPOMOCIMPLSERVICE_EXCEPTION = e;
    }

    public TehnicnaPomocImplService() {
        super(__getWsdlLocation(), TEHNICNAPOMOCIMPLSERVICE_QNAME);
    }

    public TehnicnaPomocImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEHNICNAPOMOCIMPLSERVICE_QNAME, features);
    }

    public TehnicnaPomocImplService(URL wsdlLocation) {
        super(wsdlLocation, TEHNICNAPOMOCIMPLSERVICE_QNAME);
    }

    public TehnicnaPomocImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEHNICNAPOMOCIMPLSERVICE_QNAME, features);
    }

    public TehnicnaPomocImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TehnicnaPomocImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TehnicnaPomoc
     */
    @WebEndpoint(name = "TehnicnaPomocPort")
    public TehnicnaPomoc getTehnicnaPomocPort() {
        return super.getPort(new QName("http://smart.road.si/pomoc", "TehnicnaPomocPort"), TehnicnaPomoc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TehnicnaPomoc
     */
    @WebEndpoint(name = "TehnicnaPomocPort")
    public TehnicnaPomoc getTehnicnaPomocPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://smart.road.si/pomoc", "TehnicnaPomocPort"), TehnicnaPomoc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEHNICNAPOMOCIMPLSERVICE_EXCEPTION!= null) {
            throw TEHNICNAPOMOCIMPLSERVICE_EXCEPTION;
        }
        return TEHNICNAPOMOCIMPLSERVICE_WSDL_LOCATION;
    }

}
