
package si.um.feri.obu.wsservice.avtoservis2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TehnicnaPomoc", targetNamespace = "http://smart.road.si/pomoc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TehnicnaPomoc {


    /**
     * 
     * @param napaka
     */
    @WebMethod(action = "http://smart.road.si/pomoc/odpravljanjeNapake")
    @RequestWrapper(localName = "odpravljanjeNapake", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.OdpravljanjeNapake")
    @ResponseWrapper(localName = "odpravljanjeNapakeResponse", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.OdpravljanjeNapakeResponse")
    public void odpravljanjeNapake(
        @WebParam(name = "napaka", targetNamespace = "")
        Napaka napaka);

    /**
     * 
     * @param iDobu
     */
    @WebMethod(action = "http://smart.road.si/pomoc/aktivacijaAvtovleke")
    @RequestWrapper(localName = "aktivacijaAvtovleke", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.AktivacijaAvtovleke")
    @ResponseWrapper(localName = "aktivacijaAvtovlekeResponse", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.AktivacijaAvtovlekeResponse")
    public void aktivacijaAvtovleke(
        @WebParam(name = "IDobu", targetNamespace = "")
        Integer iDobu);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://smart.road.si/pomoc/obvescanjeONapaki")
    @WebResult(name = "obvestilo", targetNamespace = "")
    @RequestWrapper(localName = "obvescanjeONapaki", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.ObvescanjeONapaki")
    @ResponseWrapper(localName = "obvescanjeONapakiResponse", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.ObvescanjeONapakiResponse")
    public String obvescanjeONapaki();

    /**
     * 
     * @param napaka
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://smart.road.si/pomoc/identificiranjeNapake")
    @WebResult(name = "sporocilo", targetNamespace = "")
    @RequestWrapper(localName = "identificiranjeNapake", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.IdentificiranjeNapake")
    @ResponseWrapper(localName = "identificiranjeNapakeResponse", targetNamespace = "http://smart.road.si/tehnicnaPomoc", className = "si.um.feri.obu.wsservice.avtoservis2.IdentificiranjeNapakeResponse")
    public String identificiranjeNapake(
        @WebParam(name = "napaka", targetNamespace = "")
        Napaka napaka);

}
