
package si.um.feri.obu.wsservice.parkirisce2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Rezervacije", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://svizec.informatika.uni-mb.si/SmartRoad/parking1/services/rezervacije/v4/Rezervacije.svc?wsdl")
public class Rezervacije
    extends Service
{

    private final static URL REZERVACIJE_WSDL_LOCATION;
    private final static WebServiceException REZERVACIJE_EXCEPTION;
    private final static QName REZERVACIJE_QNAME = new QName("http://tempuri.org/", "Rezervacije");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://svizec.informatika.uni-mb.si/SmartRoad/parking1/services/rezervacije/v4/Rezervacije.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REZERVACIJE_WSDL_LOCATION = url;
        REZERVACIJE_EXCEPTION = e;
    }

    public Rezervacije() {
        super(__getWsdlLocation(), REZERVACIJE_QNAME);
    }

    public Rezervacije(WebServiceFeature... features) {
        super(__getWsdlLocation(), REZERVACIJE_QNAME, features);
    }

    public Rezervacije(URL wsdlLocation) {
        super(wsdlLocation, REZERVACIJE_QNAME);
    }

    public Rezervacije(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REZERVACIJE_QNAME, features);
    }

    public Rezervacije(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Rezervacije(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SemicolonRezervacije
     */
    @WebEndpoint(name = "BasicHttpBinding_SemicolonRezervacije")
    public SemicolonRezervacije getBasicHttpBindingSemicolonRezervacije() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_SemicolonRezervacije"), SemicolonRezervacije.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SemicolonRezervacije
     */
    @WebEndpoint(name = "BasicHttpBinding_SemicolonRezervacije")
    public SemicolonRezervacije getBasicHttpBindingSemicolonRezervacije(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_SemicolonRezervacije"), SemicolonRezervacije.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REZERVACIJE_EXCEPTION!= null) {
            throw REZERVACIJE_EXCEPTION;
        }
        return REZERVACIJE_WSDL_LOCATION;
    }

}
