
package si.um.feri.obu.wsservice.parkirisce2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SemicolonRezervacije", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SemicolonRezervacije {


    /**
     * 
     * @param doDateTime
     * @param odDateTime
     * @param serijskaStevilkaObu
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "RezervirajParkirnoMesto", action = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11/SemicolonRezervacije/RezervirajParkirnoMesto")
    @WebResult(name = "RezervirajParkirnoMestoResult", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
    @RequestWrapper(localName = "RezervirajParkirnoMesto", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.RezervirajParkirnoMesto")
    @ResponseWrapper(localName = "RezervirajParkirnoMestoResponse", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.RezervirajParkirnoMestoResponse")
    public Integer rezervirajParkirnoMesto(
        @WebParam(name = "serijskaStevilkaObu", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
        String serijskaStevilkaObu,
        @WebParam(name = "odDateTime", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
        XMLGregorianCalendar odDateTime,
        @WebParam(name = "doDateTime", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
        XMLGregorianCalendar doDateTime);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "OdpovejRezervacijo", action = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11/SemicolonRezervacije/OdpovejRezervacijo")
    @WebResult(name = "OdpovejRezervacijoResult", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
    @RequestWrapper(localName = "OdpovejRezervacijo", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.OdpovejRezervacijo")
    @ResponseWrapper(localName = "OdpovejRezervacijoResponse", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.OdpovejRezervacijoResponse")
    public Boolean odpovejRezervacijo(
        @WebParam(name = "ID", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
        Integer id);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "SteviloPremikajocihAvtomobilov", action = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11/SemicolonRezervacije/SteviloPremikajocihAvtomobilov")
    @WebResult(name = "SteviloPremikajocihAvtomobilovResult", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
    @RequestWrapper(localName = "SteviloPremikajocihAvtomobilov", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.SteviloPremikajocihAvtomobilov")
    @ResponseWrapper(localName = "SteviloPremikajocihAvtomobilovResponse", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.SteviloPremikajocihAvtomobilovResponse")
    public Integer steviloPremikajocihAvtomobilov();

    /**
     * 
     * @param dan
     * @return
     *     returns si.um.feri.obu.wsservice.parkirisce2.ZasedonostPoDnevu
     */
    @WebMethod(operationName = "StatistikaZasedenostiPoDnevu", action = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11/SemicolonRezervacije/StatistikaZasedenostiPoDnevu")
    @WebResult(name = "StatistikaZasedenostiPoDnevuResult", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
    @RequestWrapper(localName = "StatistikaZasedenostiPoDnevu", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.StatistikaZasedenostiPoDnevu")
    @ResponseWrapper(localName = "StatistikaZasedenostiPoDnevuResponse", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11", className = "si.um.feri.obu.wsservice.parkirisce2.StatistikaZasedenostiPoDnevuResponse")
    public ZasedonostPoDnevu statistikaZasedenostiPoDnevu(
        @WebParam(name = "dan", targetNamespace = "http://www.feri.uni-mb.si/SOA/Semicolon/Rezervacije/2015/11")
        Dnevi dan);

}
