
package si.um.feri.obu.wsservice.dars1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DarsDataService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://svizec.informatika.uni-mb.si/SmartRoad/dars1/services/v2/DarsDataService.svc?wsdl")
public class DarsDataService_Service
    extends Service
{

    private final static URL DARSDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException DARSDATASERVICE_EXCEPTION;
    private final static QName DARSDATASERVICE_QNAME = new QName("http://tempuri.org/", "DarsDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://svizec.informatika.uni-mb.si/SmartRoad/dars1/services/v2/DarsDataService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DARSDATASERVICE_WSDL_LOCATION = url;
        DARSDATASERVICE_EXCEPTION = e;
    }

    public DarsDataService_Service() {
        super(__getWsdlLocation(), DARSDATASERVICE_QNAME);
    }

    public DarsDataService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DARSDATASERVICE_QNAME, features);
    }

    public DarsDataService_Service(URL wsdlLocation) {
        super(wsdlLocation, DARSDATASERVICE_QNAME);
    }

    public DarsDataService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DARSDATASERVICE_QNAME, features);
    }

    public DarsDataService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DarsDataService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DarsDataService
     */
    @WebEndpoint(name = "BasicHttpBinding_DarsDataService")
    public DarsDataService getBasicHttpBindingDarsDataService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_DarsDataService"), DarsDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DarsDataService
     */
    @WebEndpoint(name = "BasicHttpBinding_DarsDataService")
    public DarsDataService getBasicHttpBindingDarsDataService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_DarsDataService"), DarsDataService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DARSDATASERVICE_EXCEPTION!= null) {
            throw DARSDATASERVICE_EXCEPTION;
        }
        return DARSDATASERVICE_WSDL_LOCATION;
    }

}
